In [1]:
!pip install implicit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 18.6 MB 299 kB/s 


In [2]:
import json
import implicit
import pandas as pd
import scipy.sparse as sparse
import numpy as np

/usr/local/lib/python3.7/dist-packages/implicit/gpu/__init__.py:14: UserWarning: CUDA extension is built, but disabling GPU support because of 'Cuda Error: no CUDA-capable device is detected (/project/./implicit/gpu/utils.h:71)'
  f"CUDA extension is built, but disabling GPU support because of '{e}'",


In [5]:
model = implicit.als.AlternatingLeastSquares(factors=20, regularization = 0.1, iterations = 20)

/usr/local/lib/python3.7/dist-packages/implicit/utils.py:29: UserWarning: OpenBLAS detected. Its highly recommend to set the environment variable 'export OPENBLAS_NUM_THREADS=1' to disable its internal multithreading
  "OpenBLAS detected. Its highly recommend to set the environment variable "


In [7]:
loaded_model = model.load("/content/drive/MyDrive/yeoreodigm/data_files/11.01_ALS_Model")

In [8]:
matrix = sparse.load_npz('/content/drive/MyDrive/yeoreodigm/data_files/11.01_Sparse_Matrix.npz')

In [9]:
place_log = pd.read_csv("/content/drive/MyDrive/yeoreodigm/data_files/10.31_place_log.csv",index_col=0)
place_log.head(2)

member_id  place  quantity
0        184     32         1
1        184     19         1

In [10]:
members = np.sort(place_log['member_id'].unique())
user_id = np.where(members==2155)
loaded_model.recommend(userid=user_id,user_items=matrix[user_id],N=10,filter_already_liked_items=True)

(array([[53, 36, 38, 33, 32, 37, 21, 48, 44, 40]], dtype=int32),
 array([[0.02283749, 0.02066301, 0.01832768, 0.00852573, 0.00819446,
         0.00381242, 0.00166422, 0.        , 0.        , 0.        ]],
       dtype=float32))

In [24]:
entire_list = []
for member in members:
  user_id = np.where(members==member)
  recommend,score = loaded_model.recommend(userid=user_id,user_items=matrix[user_id],N=10,filter_already_liked_items=True)
  print(recommend[0])
  entire_list.append([member,recommend[0]])
  

[ 3 34 17 18  4 19 24 11  6 53]
[16 32 35  1 34 17 29 36 38  2]
[16 34 17 18 30  5 53 43 51 31]
[18 34 17 25 39  0 16 26 30  2]
[53 36 38 33 32 37 21 48 44 40]
[ 3 13 14 21 12 38  6 11 36 22]
[10  9 12 53 26 32 33  0  2 22]
[ 3 29 21 24 10 22 12 16 19  1]
[ 2  8 13 19 32 33 34 17 18  0]
[10 53 22  0 12 37  9  3 36 38]
[ 3 53 10 29 12 24 11  6 27 57]
[14 12 22 13 15 25 32 33 38 36]
[29 21 22  4 13  3  2 30 14 38]
[24 34 17 18  3 25 11  6 14  5]
[ 7 53 13  0  8 21 30 16 37 38]
[24  3 34 17 18 53 16  5 11  6]
[16  5 30 22 19 24 21  0 28 12]
[18 34 17 26 25  2 22 30  5 24]
[21 19 11 12 22 15 39 32 33 35]
[21 18 34 17 25  4 39  6 11 33]
[ 9 39 25 21  8  3 10 16  2 11]
[25  0 16 18 34 17 28 30 24  5]
[ 2 13  8 25  0 37 32 33 38 36]
[ 4 21 10 53 16  9 12 38 40 35]
[ 9 26 21  0 22  5 38 32 33 36]
[25  2  0 18 22 34 17 13 32 33]


In [26]:
recommend_result = pd.DataFrame(entire_list)

In [ ]:
recommend_result.to_pickle()